# Setting the colors
set -g default-terminal 'tmux-256color'

# Adding a second prefix key (Ctrl-a, in addition to default Ctrl-b)
set -g prefix2 C-a

# Disabling the prefix key to use tmux inside tmux (F12 to toggle)
bind -T root F12 \
  set prefix None \;\
  set prefix2 None \;\
  set key-table off \;\
  set status-style "fg=colour245,bg=colour238" \;\
  unbind -T root M-Left \;\
  unbind -T root M-Right \;\
  unbind -T root M-Up \;\
  unbind -T root M-Down \;\
  unbind -T root S-Right \;\
  unbind -T root S-Left \;\
  refresh-client -S

bind -T off F12 \
  set -u prefix \;\
  set -u prefix2 \;\
  set -u key-table \;\
  set -u status-style \;\
  bind -T root -n M-Left select-pane -L \;\
  bind -T root -n M-Right select-pane -R \;\
  bind -T root -n M-Up select-pane -U \;\
  bind -T root -n M-Down select-pane -D \;\
  bind -T root -n S-Right next \;\
  bind -T root -n S-Left prev \;\
  refresh-client -S

# Toggle synchronize-panes with
bind S \
    set synchronize-panes \;\
    display "Sync #{?synchronize-panes,ON,OFF}"

# Splitting panes with | and -
bind-key - split-window -v
bind-key = split-window -h

# Enable mouse support
set -g mouse on

# Copy and paste from system clipboard 
set -g set-clipboard on
setw -g mode-keys vi

# Key bindings for moving over panes (Alt + arrow keys)
bind-key -n M-Left select-pane -L
bind-key -n M-Right select-pane -R
bind-key -n M-Up select-pane -U
bind-key -n M-Down select-pane -D

# Switch tabs with Shift + Left/Right
bind -n S-Right next
bind -n S-Left prev

# Set the refresh interval faster
set -g status-interval 1

# Keep client attached when a session is destroyed
set-option -g detach-on-destroy off

# Kill current session cleanly and switch to another one when available
bind-key k display-menu -T 'Kill?' -x C -y C \
  'All' 9 { run-shell "\
    kr() \{ \
    for child in \$(ps -o pid= --ppid \"\$1\"); do \
      kr \"\$child\"; \
    done; \
    kill -9 \"\$1\" >/dev/null 2>&1 || true; \
    \} && \
    tmux list-panes -a -F $(printf \"\\043\{pane_pid\}\") | \
    while read -r p; do \
      kr \"\$p\"; \
    done; \
    "} \
  'Session' s { run-shell "\
    kr() \{ \
    for child in \$(ps -o pid= --ppid \"\$1\"); do \
      kr \"\$child\"; \
    done; \
    kill -9 \"\$1\" >/dev/null 2>&1 || true; \
    \} && \
    tmux list-panes -s -F $(printf \"\\043\{pane_pid\}\") | \
    while read -r p; do \
      kr \"\$p\"; \
    done; \
    "} \
  'Cancel' q {}

# Tree view with Ctrl + T
bind-key s choose-session -Z
# New window
bind-key t new-window -a -c "#{pane_current_path}"

# Reload config with prefix + r
bind-key r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Bottom bar
# Colors
# for i in {0..255}; do
#     printf '\x1b[38;5;%dmcolour%d\x1b[0m\n' $i $i
# done
set -g status-right '#[fg=colour195,bg=colour66,bold] %H:%M #[fg=colour195,bg=colour30,bold] %d.%m #[fg=colour195,bg=colour23,bold] #H '
set -g window-status-current-format '#[fg=colour195,bg=colour23,bold] #I:#W '
set -g status-style fg=black,bg=white
set -g message-style         fg=colour195,bg=colour30
set -g message-command-style fg=colour195,bg=colour20
set -g pane-border-style        fg=colour23
set -g pane-active-border-style fg=colour37